site_name: Godel
site_description: Godel, Golden's Python SDK
site_url: https://github.com/goldenrecursion/godel

theme:
  name: 'material'
  language: 'en'
  features:
    - navigation.sections
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/golden-logo-mobile.png
  favicon: images/favicon.ico

use_directory_urls: false
repo_name: goldenrecursion/godel
repo_url: https://github.com/goldenrecursion/godel
edit_uri: ''

nav:
  - Welcome: 'index.md'
  - Guides:
      - Authentication: "user_guide/Authentication"
      - Validating Triples: "user_guide/Validating Triples.ipynb"
      - Create Triples: "user_guide/Create Triples.ipynb"
      - Create Entities: "user_guide/Create Entities"
  - Reference:
    - API Reference: "api_reference.md"

markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - codehilite
  - extra

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter
