import sgqlc.types
import sgqlc.operation
import godel.schema

_schema = godel.schema
_schema_root = _schema.schema

__all__ = ('Operations',)


def query_predicate_detail():
    _op = sgqlc.operation.Operation(_schema_root.query_type, name='PredicateDetail', variables=dict(id=sgqlc.types.Arg(sgqlc.types.non_null(_schema.UUID))))
    _op_predicate = _op.predicate(id=sgqlc.types.Variable('id'))
    _op_predicate.__fragment__(fragment_predicate_details())
    _op_predicate_base_predicate_constraints = _op_predicate.base_predicate_constraints()
    _op_predicate_base_predicate_constraints_nodes = _op_predicate_base_predicate_constraints.nodes()
    _op_predicate_base_predicate_constraints_nodes.id()
    _op_predicate_base_predicate_constraints_nodes.type()
    _op_predicate_base_predicate_constraints_nodes_child_format_predicate_constraint = _op_predicate_base_predicate_constraints_nodes.child_format_predicate_constraint()
    _op_predicate_base_predicate_constraints_nodes_child_format_predicate_constraint.node_id()
    _op_predicate_base_predicate_constraints_nodes_child_format_predicate_constraint.regex_pattern()
    _op_predicate_base_predicate_constraints_nodes_child_po_predicate_constraint = _op_predicate_base_predicate_constraints_nodes.child_po_predicate_constraint()
    _op_predicate_base_predicate_constraints_nodes_child_po_predicate_constraint_po_predicate_constraint_rules_by_constraint_id = _op_predicate_base_predicate_constraints_nodes_child_po_predicate_constraint.po_predicate_constraint_rules_by_constraint_id()
    _op_predicate_base_predicate_constraints_nodes_child_po_predicate_constraint_po_predicate_constraint_rules_by_constraint_id_nodes = _op_predicate_base_predicate_constraints_nodes_child_po_predicate_constraint_po_predicate_constraint_rules_by_constraint_id.nodes()
    _op_predicate_base_predicate_constraints_nodes_child_po_predicate_constraint_po_predicate_constraint_rules_by_constraint_id_nodes.id()
    _op_predicate_base_predicate_constraints_nodes_child_po_predicate_constraint_po_predicate_constraint_rules_by_constraint_id_nodes_object_entity = _op_predicate_base_predicate_constraints_nodes_child_po_predicate_constraint_po_predicate_constraint_rules_by_constraint_id_nodes.object_entity()
    _op_predicate_base_predicate_constraints_nodes_child_po_predicate_constraint_po_predicate_constraint_rules_by_constraint_id_nodes_object_entity.__fragment__(fragment_entity_link())
    _op_predicate_base_predicate_constraints_nodes_child_enum_predicate_constraint = _op_predicate_base_predicate_constraints_nodes.child_enum_predicate_constraint()
    _op_predicate_base_predicate_constraints_nodes_child_enum_predicate_constraint_enum_predicate_constraint_elements_by_constraint_id = _op_predicate_base_predicate_constraints_nodes_child_enum_predicate_constraint.enum_predicate_constraint_elements_by_constraint_id()
    _op_predicate_base_predicate_constraints_nodes_child_enum_predicate_constraint_enum_predicate_constraint_elements_by_constraint_id_nodes = _op_predicate_base_predicate_constraints_nodes_child_enum_predicate_constraint_enum_predicate_constraint_elements_by_constraint_id.nodes()
    _op_predicate_base_predicate_constraints_nodes_child_enum_predicate_constraint_enum_predicate_constraint_elements_by_constraint_id_nodes.id()
    _op_predicate_base_predicate_constraints_nodes_child_enum_predicate_constraint_enum_predicate_constraint_elements_by_constraint_id_nodes_object_entity = _op_predicate_base_predicate_constraints_nodes_child_enum_predicate_constraint_enum_predicate_constraint_elements_by_constraint_id_nodes.object_entity()
    _op_predicate_base_predicate_constraints_nodes_child_enum_predicate_constraint_enum_predicate_constraint_elements_by_constraint_id_nodes_object_entity.__fragment__(fragment_entity_link())
    return _op


class Query:
    predicate_detail = query_predicate_detail()


class Operations:
    query = Query
