name: Docker Compose CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WALLET_A: ${{ secrets.WALLET_A }}
      WALLET_PK: ${{ secrets.WALLET_PK }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose build
    - name: Run Tests
      run: docker-compose up tests
